services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
  backend_node_modules:
